<?php
/**
 * Rkt_JsCssforSb extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE_JSSB.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       Rkt
 * @package        Rkt_JsCssforSb
 * @copyright      Copyright (c) 2015   
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */ 

/**
 * Jscss Template
 *
 * @category   Rkt
 * @package    Rkt_JsCssforSb
 * @author     Programmer-RKT
 *
 * @see Rkt_JsCssforSb_Block_Jscss
 */
?>
<?php
	$ids = explode(",",$this->getJscssIds());

	foreach ($ids as $key => $value) {
	
	    //get current entity
		$jscss = $this->getJscssEntity($value);

		//retrieves required data
	    $js = Mage::helper('rkt_jscssforsb')->modifyData($jscss->getJscssJs());
		$css = Mage::helper('rkt_jscssforsb')->modifyData($jscss->getJscssCss());
		$block_id = (int)$jscss->getBlockId();
?>

		<?php /* This script is use to put css in head */ ?>
		<script type="text/javascript">
		//<![CDATA[
			document.observe('dom:loaded', function(){
				$(document.head).insert({
					bottom: new Element('style', {'id': 'css-for-cms-block-<?php echo $block_id; ?>', type : 'text/css'})
				});
				$('css-for-cms-block-<?php echo $block_id; ?>').update('<?php print_r($css); ?>');
			});
		//]]>
		</script>

		<?php /* This script is use to hold js for cms block  */ ?>
		<script id="js-for-cms-block-<?php echo $block_id; ?>" type="text/javascript">
		//<![CDATA[
			document.observe('dom:loaded', function(){
				<?php print_r($js); ?>
			});
		//]]>
		</script>
<?php } ?>