<?php
/**
 * Rkt_JsCssforSb extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE_JSSB.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       Rkt
 * @package        Rkt_JsCssforSb
 * @copyright      Copyright (c) 2015   
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */ 

/**
 * Jscss Template
 *
 * @category   Rkt
 * @package    Rkt_JsCssforSb
 * @author     Programmer-RKT
 *
 * @see Rkt_JsCssforSb_Block_Jscss
 */
?>
<?php foreach ($this->getAllStyles() as $style) : ?>
	<style type="text/css"><?php echo $style->content; ?></style>
<?php endforeach; ?>

<?php foreach ($this->getAllScripts() as $script) : ?>
	<script type="text/javascript">//<![CDATA[
		<?php echo $script->content; ?>
	//]]></script>
<?php endforeach; ?>